{
 "title": "대전류 인가 장치 v3",
 "time": { "from": "2024-07-09T15:00:00.000Z", "to": "2024-07-10T14:59:59.000Z" },
 "panels": [
  { "title": "온도, CPU 온도, RSSI, 경고등", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "온도",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"온도1\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"온도2\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"온도3\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"온도4\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"온도5\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"온도6\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "CPU 온도",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 온도1\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 온도2\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 온도3\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 온도4\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 온도5\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 온도6\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))"
    },
    {}
   ]
  },
  {
   "title": "알람",
   "type": "alertlist",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "targets": [
    { "dataset": "mysql" }
   ]
  },
  {
   "title": "센서 경고등",
   "type": "stat",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: -1)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor1\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"value1\")\r\n  |> last() \r\n  |> map(fn: (r) => ({\r\n    _field: \"1번 센서\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor2\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"value1\")\r\n  |> last()\r\n    |> map(fn: (r) => ({\r\n    _field: \"2번 센서\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor3\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"value1\")\r\n  |> last()\r\n    |> map(fn: (r) => ({\r\n    _field: \"3번 센서\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor4\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"value1\")\r\n  |> last()\r\n    |> map(fn: (r) => ({\r\n    _field: \"4번 센서\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor5\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"value1\")\r\n  |> last()\r\n    |> map(fn: (r) => ({\r\n    _field: \"5번 센서\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: -1m)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"sensor6\")\r\n  |> filter(fn: (r) => r[\"tag1\"] == \"value1\")\r\n  |> last()\r\n    |> map(fn: (r) => ({\r\n    _field: \"6번 센서\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"RSSI1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"RSSI1\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"RSSI2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"RSSI2\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"RSSI3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"RSSI3\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"RSSI4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"RSSI4\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"RSSI5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"RSSI5\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"RSSI6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"RSSI6\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "현재온도 및 예측온도",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"센서1 온도\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"센서2 온도\",\r\n    _time: r._time, \r\n    _value: r._value/10\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"센서3 온도\",\r\n    _time: r._time, \r\n    _value: r._value/10\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_temperature1\")\r\n  |> map(fn: (r) => ({\r\n      _field: \"센서1 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_temperature2\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"센서2 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_temperature3\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"센서3 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"센서4 온도\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"센서5 온도\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"Temperature6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"센서6 온도\",\r\n    _time: r._time,\r\n    _value: r._value/10\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_temperature4\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"센서4 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_temperature5\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"센서5 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_temperature6\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"센서6 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    }
   ]
  },
  {
   "title": "현재 CPU 온도 및 예측 온도",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 센서1 온도\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 센서2 온도\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 센서3 온도\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 센서4 온도\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 센서5 온도\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"CPU Temperature6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"CPU 센서6 온도\",\r\n    _time: r._time, \r\n    _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_cpu_temperature1\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"CPU 센서1 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_cpu_temperature2\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"CPU 센서2 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_cpu_temperature3\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"CPU 센서3 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_cpu_temperature4\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"CPU 센서4 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_cpu_temperature5\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"CPU 센서5 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    },
    {
     "query": "from(bucket: \"modbus2\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"predict02\" and r[\"_field\"] == \"predict_cpu_temperature6\")\r\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_start\", \"_stop\"])\r\n  |> map(fn: (r) => ({\r\n      _field: \"CPU 센서6 예측온도\",\r\n      _time: r._time, \r\n      _value: r._value\r\n  }))"
    }
   ]
  },
  { "title": "진동", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 13 },
   "options": {
    "content": "<h6 style=\"text-align:center; font-size:10px;\">센서 1<h6>"
   }
  },
  {
   "title": "센서 1 진동 차트",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"x1\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"y1\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"z1\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "X",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"x1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n|> last()\r\n\r\n\r\n"
    },
    {}
   ]
  },
  {
   "title": "Y",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"y1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n|> last()"
    },
    {}
   ]
  },
  {
   "title": "Z",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"z1\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Z\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n|> last()"
    },
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 17 },
   "options": {
    "content": "<h6 style=\"text-align:center; font-size:10px;\">센서 2<h6>"
   }
  },
  {
   "title": "센서 2 진동 차트",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"x2\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"y2\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"z2\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "X",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n|> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n"
    },
    {}
   ]
  },
  {
   "title": "Y",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n|> aggregateWindow(every: 30s, fn: mean, createEmpty: false)\r\n"
    },
    {}
   ]
  },
  {
   "title": "Z",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z2\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Z\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 21 },
   "options": {
    "content": "<h6 style=\"text-align:center; font-size:10px;\">센서 3<h6>"
   }
  },
  {
   "title": "센서 3 진동 차트",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"x3\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"y3\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"z3\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "X",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {}
   ]
  },
  {
   "title": "Y",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {}
   ]
  },
  {
   "title": "Z",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z3\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Z\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 25 },
   "options": {
    "content": "<h6 style=\"text-align:center; font-size:10px;\">센서 4<h6>"
   }
  },
  {
   "title": "센서 4 진동 차트",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"x4\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"y4\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"z4\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "X",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n\r\n\r\n"
    },
    {}
   ]
  },
  {
   "title": "Y",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Y\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {}
   ]
  },
  {
   "title": "Z",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z4\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Z\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 29 },
   "options": {
    "content": "<h6 style=\"text-align:center; font-size:10px;\">센서 5<h6>"
   }
  },
  {
   "title": "센서 5 진동 차트",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"x5\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"y5\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"z5\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "X",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"x5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n  |> last()\r\n\r\n\r\n\r\n"
    },
    {}
   ]
  },
  {
   "title": "Y",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"y5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n  |> last()\r\n"
    },
    {}
   ]
  },
  {
   "title": "Z",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"z5\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Z\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n|> last()\r\n\r\n"
    },
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 9, "x": 0, "y": 33 },
   "options": {
    "content": "<h6 style=\"text-align:center; font-size:10px;\">센서 6<h6>"
   }
  },
  {
   "title": "센서 6 진동 차트",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"x6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"x6\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"y6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"y6\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    },
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5d)\r\n|> filter(fn: (r) => r._field == \"z6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"z6\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n"
    }
   ]
  },
  {
   "title": "X",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"x6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n  |> last()\r\n\r\n\r\n\r\n"
    },
    {}
   ]
  },
  {
   "title": "Y",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"y6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"X\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n  |> last()\r\n\r\n"
    },
    {}
   ]
  },
  {
   "title": "Z",
   "type": "gauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "massmg" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket:\"modbus2\")\r\n|> range(start: -5m)\r\n|> filter(fn: (r) => r._field == \"z6\")\r\n|> map(fn: (r) => ({\r\n    _field: \"Z\",\r\n    _time: r._time,\r\n    _value: r._value\r\n  }))\r\n  |> last()\r\n\r\n"
    },
    {}
   ]
  }
 ]
}